config/routes.rb
Rails.application.routes.draw do
  resources :meditations, only: [:new, :create, :index]
  resources :static_pages do
    collection do
      get "landing"
      get "home"
      get "about_the_project"
    end
  end

  root to: "static_pages#landing"

end

app/models/meditation.rb
class Meditation < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/meditations_controller.rb
class MeditationsController < ApplicationController
  def create
  end

  def index
    @meditations = Meditation.all
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing
  end

  def home
  end

  def about_the_project
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meditations_helper.rb
module MeditationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UberMeditation</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <audio id="audio" src="http://www.buddhanet.net/filelib/audio/gong-burmese.wav" autostart="false" ></audio>
  <link href='https://fonts.googleapis.com/css?family=Source+Serif+Pro:400,600,700' rel='stylesheet' type='text/css'>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="navbar-brand brandtext"><%= link_to "Uber Meditation", landing_static_pages_path %></span></div>
    </div>
    <ul class="nav navbar-nav">
      <li class="nav-item"> 
        <%= link_to "Learn", home_static_pages_path %>
      </li>
      <li class="nav-item">
        <%= link_to "Practice", new_meditation_path %>
      </li>
      <li class="nav-item"> 
        <%= link_to "Reflect", meditations_path %>
      </li>
    <li class="nav-item">
        <%= link_to "About the Project", about_the_project_static_pages_path %>
      </li>
    </ul>
  </div>
</nav>

<%= yield %>

<div class="container">
  <footer class="footer">
    <span>
      <p class="navbar-text">
        Jessica J. Kim 
      </p>
      <p class="navbar-text">
        <a href="https://github.com/adoseofjess/UberMeditation">Source Code</a>
      </p>
      <p class="navbar-text">
        <a href="https://www.linkedin.com/in/jessicajk">LinkedIn</a>
      </p>
      <p class="navbar-text">
        <a href="mailto:jessjkim@gmail.com">Contact Me</a>
      </p>
    </span>
  </footer>
</div>
</body>
</html>

app/views/meditations/create.html.erb
<h1>Meditations#create</h1>
<p>Find me in app/views/meditations/create.html.erb</p>

app/views/meditations/index.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Past Meditations</h3>
    </div>
    <div class="panel-body">
      <table class="table table-hover">
        <tr>
          <th>Start</th>
          <th>End</th>
          <th>Notes</th>
        </tr>
        <% @meditations.each do |meditation| %>
          <tr>
            <td><%= meditation.start_time.strftime("%m/%d/%y %H:%M") %></td>
            <td><%= meditation.end_time.strftime("%m/%d/%y %H:%M") %></td>
            <td><%= meditation.post_notes %></td>
          </tr>
        <% end %>
      </table>
  </div>
</div>

app/views/meditations/new.html.erb
<div class="landing">
  <div id="main"></div>
</div>

app/views/static_pages/about_the_project.html.erb
<div class="container about-the-project-container">
  <div class="about-the-project-content">
    <p class="lead about-the-project-header">about the project</p>
    <p>Uber Meditation is a web application for Uber employees to learn how to meditate in order to deal with stress and find peace. I envisioned this as a stand-alone web application, linked to by relevant Hipchat chatrooms and internal wikis within the company.</p>
    <p class="lead about-the-project-header">current and future functionality</p>
    <p>Currently, users can browse various meditation techniques, read detailed instructions, and practice meditation with the help of a timer. There is a page where users can view information about their past meditation sessions, currently seeded with fake data.</p>
    <p>In the future, they might also log in, see more detailed stats about their past meditation sessions, schedule upcoming meditation sessions, and sign up for SMS and email alerts.</p>
    <p class="lead about-the-project-header">content and design philosophy</p>
    <p>Uber employees are busy, so I aimed to: 
    <ul>
      <li>keep the content short and simple</li>
      <li>keep the design light and inviting</li> 
      <li>keep it action-oriented</li>
    </ul>
      <p>For example, on the “Learn” tab, the meditation techniques are shown on cards that resemble Post-It Notes to make it look fun and approachable.</p>
      <p>For each meditation technique, there are very short descriptions and only a couple of instruction bulletpoints, with a button to start meditating and learn while doing.</p>
    <p class="lead about-the-project-header">prototypes</p>
    <p>The previous tabs show my prototypes of UberMeditation’s landing page ("Uber Meditation" tab), digital learning exercise ("Learning" tab), practice page ("Practice" tab), and reflect page ("Reflect" tab).</p>
    <ul>
    <li>The landing page is a simple page with a title, description, and a call to action button to start learning.</li>
    <li>On the learning page, users can scan different meditation techniques, click to see more detailed instructions, and start meditating. The main hope was for users to actually practice meditation, so I didn’t see the need for a lot of text.</li>
    <li>The practice page shows a meditation timer with short and long session presets. You can adjust the time. You can pause and reset the timer.</li>
    <li>The reflect page shows a log of a user's meditation sessions with notes, currently seeded with false data.</li>
    </ul>
    <p class="lead about-the-project-header">future designs</p>
    <p>I created prototypes for the landing page and other features of this digital internal learning platform, so I worked on two screen mockups of future features I envisioned.</p>
    <p class="lead about-the-project-subheader">collect more data about individuals' meditations</p>
    <p>I liked the idea of collecting more data on an individual level about meditation sessions. Users would be able to log their meditation sessions and add notes, and see some statistics. This would give users insights into any longitudinal trends.</p>
    <%= image_tag "wireframe1.jpg", height: "600", width: "400", class: "wireframe" %>
    <p>For example, in this mockup, a user is viewing her "Past Meditations" page. She sees a time-based graph about her meditation sessions and below that she sees a log of her meditation sessions, including her notes.</p>
    <p class="lead about-the-project-subheader">schedule future meditation sessions and receive alerts</p>
    <p>A concern I had was making it easy for Uber employees to stay accountable and continue to practice meditation. Even though users want to devote time to meditation, they may easily forget to do it.</p>
    <p>One idea I had was meeting Uber employees where they already spend a lot of time by allowing users to schedule upcoming meditation sessions and sign up for alerts.</p>
    <%= image_tag "wireframe2.jpg", height: "600", width: "400", class: "wireframe" %>
    <p>In this mockup, a user is viewing her upcoming meditation sessions and can create new ones. She can edit or delete these sessions. She can also choose to sign up for SMS and/or email alerts for reminders.</p>
    <p class="lead about-the-project-header">tools used</p>
    <ul>
      <li>Ruby on Rails</li>
      <li>React.js</li>
      <li>Bootstrap SASS</li>
      <li>Balsamiq</li>
      <li>Learned about meditation from this blog: http://liveanddare.com/types-of-meditation/</li>
    </ul>
    <p class="lead about-the-project-header">trade-offs or what I would have done differently?</p>
    <p>I had a lot of feature ideas but implemented the ones I thought were most important due to limited time.</p>
    <p>Overall, I had a good time learning about meditation and working on the project!
    </p>
  </div>
</div>

app/views/static_pages/landing.html.erb
<div class="landing">
  <div class="jumbotron meditation-jumbotron">
    <div class="title">
      <h1>Take the time today.</h1>
    </div>
    <div class="description">
      Even five minutes of meditation can help alleviate stress and helps you stay balanced.
    </div>
    <p><a class="btn btn-primary btn-lg" href=<%=home_static_pages_url%> role="button">Learn more</a></p>
  </div>
</div>